version: "3.9"
services:

  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - /usr/local/bin
    environment:
      - MYSQL_ROOT_PASSWORD=dsrm
      - MYSQL_PASSWORD=dsrm
      - MYSQL_USER=dsrm
      - MYSQL_DATABASE=mariatest

  dsrm-backend:
    container_name: dsrm-backend
    image: dsrm-backend
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dsrm
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mariadb://localhost:3306/dsrm
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=dsrm
    depends_on:
      - mariadb
    ports:
      - 8080:8080

  dsrm-frontend:
    build: ./dsrm-frontend
    container_name: dsrm-frontend
    depends_on:
      - dsrm-backend
    ports:
      - 4200:80


